# Dockerfile.frontend
# Node.js 20 버전을 기반 이미지로 사용
FROM node:20-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# 컨테이너 내에서 작업할 디렉토리를 설정합니다.
WORKDIR /workspaces/Dreamseekers-FE

# 컨테이너 사용자 설정 (보안상 root 대신 node 사용자 권장)
USER node