# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - uses: actions/setup-node@v4.4.0
              with:
                  node-version: "20"
                  # cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - run: npm run build
              env:
                  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
                  VITE_NAVER_MAPS_CLIENT_ID: ${{ secrets.VITE_NAVER_MAPS_CLIENT_ID }}
                  CI: false
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3.0.1
              with:
                  # Upload entire repository
                  path: "./dist"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4.0.5
